### ISSUE TITLE
Packagist not updated with 2.0.2 tag

### ISSUE THREAD

**Issue by adampatpattison** [marionnewlevant/craft-snitch#10]
Hi Marion, 

When manually building from composer for the latest version of Snitch I am getting the following issue:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package marionnewlevant/snitch 2.0.2 exists as marionnewlevant/snitch[2.0.0, 2.0.1, v2.x-dev] but these are rejected by your constraint.
```
If you look on the packagist setting, the tags haven't been updated to include 2.0.2

**Comment by adampatpattison** [comment]
Bump?

**Comment by j2is** [comment]
Hey also getting this issue, any chance of an update?

**Comment by marionnewlevant** [comment]
I don't know why it didn't happen automatically, but doing it manually seems to have fixed it.
