### ISSUE TITLE
froala install error after update

### ISSUE THREAD

**Issue by jlamb1** [marionnewlevant/craft-snitch#12]
I think related to #11, updating the snitch plugin brings down my local env with the error `Call to a member function getSettings() on null`.

I had this error originally when I had both Froala WYSIWYG Editor installed in tandem with the two-factor authentication plugin. I uninstalled the two-factor plugin and everything started working.

I saw this error pop back up again today after updating snitch, more details & stacktrace here:

https://github.com/froala/Craft-3-Froala-WYSIWYG/issues/11

I'm not sure if this is on your end or theirs, but wanted to bring it to your attention - the common denominator seems to be the two-factor plugin

**Comment by marionnewlevant** [comment]
What Snitch is doing is calling Craft::$app->getUser()->getIsGuest() which is getting the custom fields, which calls the froala Field->init() before the froala module is loaded.

Problem on their end, but doesn't look intractable

**Comment by jlamb1** [comment]
thanks @marionnewlevant ! This lines up with the PR i'm seeing, so makes sense https://github.com/froala/Craft-3-Froala-WYSIWYG/pull/12
