### ISSUE TITLE
404 for Snitch.js & Snitch.css

### ISSUE THREAD

**Issue by Saboteur777** [marionnewlevant/craft-snitch#13]
I get 404s on Snitch CP assets, like this: `/cpresources/3a4fe824/css/Snitch.css`

Craft 3.1.26
Snitch 2.1.0

**Comment by marionnewlevant** [comment]
@Saboteur777 Try deleting the entire /cpresources directory

**Comment by Saboteur777** [comment]
Tried that, the issue still persists.

**Comment by marionnewlevant** [comment]
Probably a case issue - you are looking for `Snitch.css`, but what is there is `snitch.css`
I need to make my file names lowercase. Should be fixed in 2.1.2. Many thanks for reporting it!

**Comment by Saboteur777** [comment]
Thanks for the quick fix!
