### ISSUE TITLE
InvalidConfigException Unable to locate message source for category 'typedlinkfield'.

### ISSUE THREAD

**Issue by dlindberg** [marionnewlevant/craft-snitch#15]
### Description

There is a difficult to diagnose issue introduced with the Craft 3.3+ update that can cause  `yii\base\InvalidConfigException` if a plugin [assumes the craft app is fully bootstrapped during the `init()` method](https://github.com/craftcms/cms/issues/4944#issuecomment-532258934).  The specific issue occurs when using the sebastianlenz/linkfield plugin as reported in [issue 79 on that plugin](https://github.com/sebastian-lenz/craft-linkfield/issues/79) where the [CpFieldInspect-Craft also trigged the issue](https://github.com/mmikkel/CpFieldInspect-Craft/issues/14) (From the discussion, [diagnosing the problem proved challenging](https://github.com/mmikkel/CpFieldInspect-Craft/issues/14#issuecomment-544685026), but [the specific solution appears relatively straight forward](https://github.com/mmikkel/CpFieldInspect-Craft/commit/1a35bcef471e35f04dda910067b210611daf8a75).

### Steps to reproduce

1. Install the Craft Snitch Plugin
2. Install another plugin that modifies the application configuration (e.g. [sebastianlenz/linkfield](https://github.com/sebastian-lenz/craft-linkfield))

### Additional info

- Plugin version: 3.0.0
- Craft version: 3.3.17

**Comment by marionnewlevant** [comment]
Thanks for the very clear report!
