### ISSUE TITLE
Snitch didn't report even multiple users are editing same entry

### ISSUE THREAD

**Issue by hongc-cc** [marionnewlevant/craft-snitch#17]
Step to reproduce:

1. Get Craft cms on v3.5.5
2. Install sninch v3.0.1
3. Get to entry 1
4. open incognito window, login as another useer, go to entry 1.
5. wait...nothing happens
6. check database, found this:

![Screenshot 2020-08-23 at 3 32 16 PM](https://user-images.githubusercontent.com/7658690/90973633-81738080-e556-11ea-95d7-cd115e6316de.png)

**Comment by marionnewlevant** [comment]
Thanks for reporting! Should be fixed in 3.0.2
