### ISSUE TITLE
Composer deprecation notice

### ISSUE THREAD

**Issue by daltonrooney** [marionnewlevant/craft-snitch#20]
When running composer install, I get the following message:

```
Deprecation Notice: Class marionnewlevant\snitch\assetbundles\Snitch\SnitchAsset located in ./vendor/marionnewlevant/snitch/src/assetbundles/snitch/SnitchAsset.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

**Comment by daltonrooney** [comment]
Found [this comment](https://github.com/bhashkar007/guest-entries-notification/issues/6#issue-729836078) from @brandonkelly on another plugin with a similar issue, if it helps!

**Comment by brandonkelly** [comment]
Looks like this was already fixed in 3.0.3 per this commit: ace43106d0b2b8d3ab572074341211229d172cba

**Comment by brandonkelly** [comment]
I’m not seeing the deprecation error when installing 3.0.3 with Composer 1, so can verify the fix worked.

**Comment by daltonrooney** [comment]
Thanks @brandonkelly, I thought I was up to date, I should have double-checked!
