### ISSUE TITLE
3.0.4 update causes Craft to completely crash

### ISSUE THREAD

**Issue by FlorisDerks** [marionnewlevant/craft-snitch#21]
When I update the plugin to the new 3.0.4 version, the whole admin panel crashes with the message "Class 'born05\twofactorauthentication\Plugin' not found" (since I don't use that plugin). I see that there is an attempt to check if the plugin is installed, but that doesn't seem to be enough to prevent this error from occurring.

**Comment by craftedsystems** [comment]
Snitch expects the _two factor authentication_ plugin of _born05_. You can either roll back snitch or install https://plugins.craftcms.com/two-factor-authentication

to roll back …
`composer require marionnewlevant/snitch:3.0.3`

**Comment by craftedsystems** [comment]
Snitch seems to expect the _two-factor authentication_ plugin of _born05_.  
You can either roll back snitch or install https://plugins.craftcms.com/two-factor-authentication.

As I don't use this plugin, I decided to roll back.
`composer require marionnewlevant/snitch:3.0.3`

**Comment by marionnewlevant** [comment]
Aack! I think I have that fixed now. - Version 3.0.4.1
