### ISSUE TITLE
Time Out Takes Too Long

### ISSUE THREAD

**Issue by chrisjbr** [marionnewlevant/craft-snitch#3]
I found that the expiry seems to take a while. If one user visits an existing Entry, waits a second and then leaves it, the plugin will report to other users that the first user is still there for a couple of minutes. My `serverPollInterval` set to something short like 10 seconds.

I believe the bug is on `craft-snitch/mnsnitch/services/MnSnitchService.php`, line 73:
`$timeOut = craft()->config->get('serverPollInterval', 'mnsnitch') * 10;`

By removing the ` * 10` from this line, the expiry time seems to reflect the `serverPollInterval` value.

Hope this is useful feedback, and thank you so much for this plugin, it is fantastic!

**Comment by marionnewlevant** [comment]
I worry that if the first user visits an existing Entry for only a short time, but changes it in that short time, that other users may never notice that that first user was there (and may have changed the entry) unless the report hangs around for awhile.

So glad you are getting good use out of the plugin!
